version: '3'

services:
    nginx-proxy:
        image: nginx:1.13
        ports:
            - '80:80'
        volumes:
            - nginx-proxy-conf:/etc/nginx/conf.d
            - nginx-proxy-vhost:/etc/nginx/vhost.d
            - nginx-proxy-certs:/etc/nginx/certs:ro
            - nginx-proxy-challenges:/usr/share/nginx/html
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

    docker-gen:
        image: arnellebalane/snippets-docker-gen:1.0
        command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        depends_on:
            - nginx-proxy
        volumes:
            - nginx-proxy-conf:/etc/nginx/conf.d
            - nginx-proxy-vhost:/etc/nginx/vhost.d
            - nginx-proxy-certs:/etc/nginx/certs:ro
            - nginx-proxy-challenges:/usr/share/nginx/html
            - /var/run/docker.sock:/tmp/docker.sock:ro
        labels:
            - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        depends_on:
            - nginx-proxy
            - docker-gen
        volumes:
            - nginx-proxy-conf:/etc/nginx/conf.d
            - nginx-proxy-vhost:/etc/nginx/vhost.d
            - nginx-proxy-certs:/etc/nginx/certs:rw
            - nginx-proxy-challenges:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro

    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb

    web:
        image: arnellebalane/snippets-web:1.0
        command: etc/entrypoint.sh start
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        image: arnellebalane/snippets-nginx:1.0
        depends_on:
            - nginx-proxy
            - docker-gen
            - web
        env_file: nginx/.env

volumes:
    nginx-proxy-conf:
    nginx-proxy-certs:
    nginx-proxy-vhost:
    nginx-proxy-challenges:
