version: '3'

services:
    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb

    web:
        build: .
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        depends_on:
            - web
