version: '3'

services:
    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb

    web:
        build: .
        command: etc/entrypoint.sh dev
        volumes:
            - ./source:/app/source
            - ./etc:/app/etc
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        volumes:
            - ./build:/usr/share/nginx/html
        depends_on:
            - web
        environment:
            VIRTUAL_HOST: snippets.local

    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - '3000:80'
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
