version: '3'

services:
    web:
        build: .
        volumes:
            - ./source:/app/source
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        image: nginx:1.13
        volumes:
            - ./build:/usr/share/nginx/html
            - ./etc/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - web

    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb
