version: '3'

services:
    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb

    web:
        build: .
        command: etc/entrypoint.sh dev
        volumes:
            - ./source:/app/source
            - ./etc:/app/etc
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        volumes:
            - ./build:/usr/share/nginx/html
        depends_on:
            - web
        environment:
            VIRTUAL_HOST: snippets.local

    nginx-proxy:
        image: nginx:1.13
        ports:
            - '3000:80'
        volumes:
            - nginx-proxy-conf:/etc/nginx/conf.d

    docker-gen:
        build: docker-gen
        command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
        volumes:
            - nginx-proxy-conf:/etc/nginx/conf.d
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - ./docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl

volumes:
    nginx-proxy-conf:
