version: '3'

services:
    web:
        build: .
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        image: nginx:1.13
        depends_on:
            - web

    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb
