version: '3'

services:
    web:
        build: .
        volumes:
            - .:/app
        depends_on:
            - postgres
        env_file:
            - .env

    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb
