version: '3'

services:
    web:
        build: .
        command: etc/docker.sh dev
        volumes:
            - .:/usr/src/app
        ports:
            - '3000:3000'
        depends_on:
            - database
        environment:
            DATABASE_URL: postgres://snippetsuser@database:5432/snippetsdb
            SECURITY_CSRF: 'false'

    database:
        image: postgres:9.6
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb
