version: '3'

services:
    postgres:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb

    web:
        image: arnellebalane/snippets-web
        command: etc/entrypoint.sh start
        depends_on:
            - postgres
        env_file:
            - .env

    nginx:
        image: arnellebalane/snippets-nginx
        ports:
            - '80:80'
        depends_on:
            - web
