version: '3'

services:
    web:
        build: .
        command: etc/entrypoint.sh dev
        volumes:
            - .:/usr/src/app
        ports:
            - '3000:3000'
        depends_on:
            - database
        environment:
            DATABASE_URL: postgres://snippetsuser@database/snippetsdb
            SECURITY_CSRF: 'false'

    database:
        image: postgres:10.3
        environment:
            POSTGRES_USER: snippetsuser
            POSTGRES_DB: snippetsdb
